id: P005393
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG1286
  title: བཀའ་བརྒྱུད་པའི་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་ཁག་ཅིག་དང་ཁྲིད་ཡིག་སོགས།
  author: ''
  volumes:
    9e78e32327684d59b5a361851d2eeca0:
      image_group_id: I1KG12677
      title: ''
      volume_number: 1
      total_pages: 856
      base_file: v001.txt
