id: I8A9349E9
legacy_id: P005393
ocr_import_info:
  bdrc_scan_id: W1KG1286
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T20:10:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:40:51.705425+00:00'
last_modified: 2022-08-31 11:41:47.560449
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG1286
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG1286
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀའ་བརྒྱུད་པའི་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་ཁག་ཅིག་དང་ཁྲིད་ཡིག་སོགས།
statistics:
  ocr_word_mean_confidence_index: 0.679584841655409
  ocr_word_median_confidence_index: 0.7200000286102295
quality: null
bases:
  I1KG12677:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12677
      total_pages: 856
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12677.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.679584841655409
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
