id: I8A9349E9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:16:01+00:00'
last_modified: '2022-06-08T02:46:00.926507+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1286
  title: བཀའ་བརྒྱུད་པའི་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་ཁག་ཅིག་དང་ཁྲིད་ཡིག་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    60E1:
      image_group_id: I1KG12677
      title: ''
      total_pages: 856
      order: 1
      base_file: 60E1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
